/**
 * Validates the environment against `src/lib/env/spec.ts`, and regenerates
 * `.env.example` from it.
 *
 *   npm run env:check                       # check every process
 *   npm run env:check -- --scope=worker      # check just the worker
 *   npm run env:check -- --write-example     # rewrite .env.example
 *
 * Run before starting the worker: a missing Podio token discovered forty minutes
 * into a queue costs more than a two-second check does.
 *
 * Secret values are never printed — only whether they are set.
 *
 * `.mts` so node treats it as ESM; the `.ts` import specifier below is required
 * because plain `node` (native type stripping) does not resolve extensionless
 * paths the way the Next.js bundler does.
 */

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import {
  ENV_VARS,
  PROCESS_SCOPES,
  specsForScopes,
  type EnvScope,
  type EnvVarSpec,
} from "../src/lib/env/spec.ts";

// `@next/env` is CommonJS; a named ESM import of it fails under plain node.
const { loadEnvConfig } = createRequire(import.meta.url)(
  "@next/env",
) as typeof import("@next/env");

const projectDir = process.cwd();
loadEnvConfig(projectDir, process.env.NODE_ENV !== "production");

const args = process.argv.slice(2);
const wantsExample = args.includes("--write-example");
const scopeArg = args.find((arg) => arg.startsWith("--scope="))?.split("=")[1];

if (wantsExample) {
  const target = path.join(projectDir, ".env.example");
  writeFileSync(target, renderExample(), "utf8");
  console.log(`Wrote ${path.relative(projectDir, target)}`);
}

const processes: (keyof typeof PROCESS_SCOPES)[] =
  scopeArg === "worker" || scopeArg === "web"
    ? [scopeArg]
    : ["web", "worker"];

let failed = false;

for (const processName of processes) {
  const scopes: readonly EnvScope[] = PROCESS_SCOPES[processName];
  const specs = specsForScopes(scopes);
  const missing: EnvVarSpec[] = [];

  console.log(`\n${processName}:`);

  for (const spec of specs) {
    const raw = process.env[spec.name]?.trim();
    const value = raw && raw !== "" ? raw : spec.default;
    const source = raw && raw !== "" ? "env" : value ? "default" : "unset";

    if (!value && spec.required) {
      missing.push(spec);
      console.log(`  MISSING  ${spec.name}`);
      continue;
    }
    if (!value) {
      console.log(`  unset    ${spec.name} (optional)`);
      continue;
    }

    console.log(`  ok       ${spec.name} = ${display(spec, value)} [${source}]`);
  }

  if (missing.length > 0) {
    failed = true;
    console.log(
      `\n  ${missing.length} required variable(s) missing for ${processName}. ` +
        `Copy .env.example to .env.local and fill them in.`,
    );
  }
}

console.log("");
process.exit(failed ? 1 : 0);

/** Secrets are reported as set, never echoed — this output lands in terminals and CI logs. */
function display(spec: EnvVarSpec, value: string): string {
  if (spec.secret) return `set (${value.length} chars, hidden)`;
  return value.length > 60 ? `${value.slice(0, 57)}...` : value;
}

function renderExample(): string {
  const lines: string[] = [
    "# Generated by `npm run env:check -- --write-example`. Edit src/lib/env/spec.ts, not this file.",
    "#",
    "# Copy to .env.local and fill in real values. .env.local is gitignored;",
    "# this file is committed and must never contain a real credential.",
    "# Storage guidance: docs/env-and-secrets.md",
    "",
  ];

  let currentScope: EnvScope | null = null;

  for (const spec of ENV_VARS) {
    if (spec.scope !== currentScope) {
      currentScope = spec.scope;
      lines.push(`# ${"=".repeat(74)}`);
      lines.push(`# ${scopeHeading(currentScope)}`);
      lines.push(`# ${"=".repeat(74)}`);
      lines.push("");
    }

    lines.push(`# ${spec.description}`);
    if (spec.doc) lines.push(`# See ${spec.doc}`);
    if (spec.secret) lines.push("# SECRET — never commit, never log, never NEXT_PUBLIC_.");
    if (!spec.required) lines.push("# Optional — commented out means the default applies.");
    lines.push(
      `${spec.required ? "" : "# "}${spec.name}=${spec.default ?? spec.example ?? ""}`,
    );
    lines.push("");
  }

  return lines.join("\n");
}

function scopeHeading(scope: EnvScope): string {
  switch (scope) {
    case "shared":
      return "Shared — read by both the web dashboard and the worker";
    case "worker":
      return "Worker only — the publishing process";
    case "web":
      return "Web only — the Next.js dashboard (server side)";
    case "public":
      return "Public — inlined into the browser bundle at build time. Never secret.";
  }
}
